# Generated by Django 5.2.12 on 2026-03-29 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('leave', 'Leave dataset'), ('burnout', 'Burnout dataset')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='datasets/%Y/%m/%d/')),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='csvreport',
            name='analytics_a_user_id_87adc7_idx',
        ),
        migrations.AlterField(
            model_name='csvreport',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hrdataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='csvreport',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics_app.hrdataset'),
        ),
        migrations.AddIndex(
            model_name='csvreport',
            index=models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_29c43b_idx'),
        ),
        migrations.AddIndex(
            model_name='hrdataset',
            index=models.Index(fields=['user', 'kind', 'is_active', 'created_at'], name='analytics_a_user_id_c476d0_idx'),
        ),
    ]
